on: [push]

job:
  test:
    runs-on: ubuntu-latest
    name: Lint and Test
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v4
      with:
        node-version: "22.x"
        cache: "npm"
        cache-dependency-path: code/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm test
      