name: 'SAP BTP Update SaaS Subscriptions'
description: 'Updates all SaaS subscriptions for a multitenant application in SAP BTP'
inputs:
  api-url:
    description: 'The URL of the SaaS Provisioning Service API'
    required: true
  token-url:
    description: 'The URL of the token endpoint'
    required: true
  client-id:
    description: 'Client ID for OAuth2 authentication'
    required: true
  client-secret:  
    description: 'Client secret for OAuth2 authentication'
    required: true
  timeout:
    description: 'Timeout in seconds'
    required: false
    default: 120
  interval:
    description: 'Check interval in seconds'
    required: false
    default: 5
runs:
  using: 'node20'
  main: 'dist/index.js'
